apiVersion: v1
kind: Service
metadata:
  name: cilium-prometheus
  namespace: kube-system
  labels:
    k8s-app: cilium
spec:
  ports:
    - name: prometheus
      port: 9962
      targetPort: 9962
  selector:
    k8s-app: cilium

