#values.yaml
k8sServiceHost: "193.196.39.140"
k8sServicePort: "6443"

kubeProxyReplacement: true

l2announcements:
  enabled: true

externalIPs:
  enabled: true

#增加 Cilium 與 Kubernetes API Server 的請求速率限制
k8sClientRateLimit:
  qps: 50     # (Queries Per Second）表示每秒最多 50 個請求
  burst: 200   #  API 允許的瞬時最大請求數（突發流量）

operator:
  # 如果只有一台 Node，請取消註解這行
  # replicas: 1  
  rollOutPods: true

rollOutCiliumPods: true

ingressController:
  enabled: true
  default: true
  loadbalancerMode: shared
  nodeSelector:
    kubernetes.io/os: linux  # 讓所有 Linux 節點（包括 Worker）運行 Cilium Ingress
  service:
    annotations: {}  # 刪除 `io.cilium/lb-ipam-ips`
      #io.cilium/lb-ipam-ips: 193.196.39.240     #如果真的需要手動指定 IP，選擇一個 193.196.36.x 或 193.196.39.x 範圍內的可用 IP

